kind = "web"
previewPath = "/"
title = "Lahori Zeera"
version = "1.0.0"
id = "artifacts/lahori-zeera"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25534

[services.development]
run = "pnpm --filter @workspace/lahori-zeera run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/lahori-zeera", "run", "build" ]
publicDir = "artifacts/lahori-zeera/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25534"
BASE_PATH = "/"
